function [good,weird,weirdbad,bad] = thegoodthebadandtheweird(x,y,xt,yt)

% The weird
weird = y > yt & x<xt & ...
    (x>quantile(x(...
    x<xt & y > yt),0.85) | ...
    y < quantile(y(...
    x<xt & y > yt),0.2));

% The good
if numel(x)<40
    good = x<vars.Distance_threshold &...
        y > yt & ~weird;
else
    good = x<quantile(x(x<xt),0.2) &...
        y > yt; %*goodspikeAmp;
end

% The borderline
weirdbad = (x>xt & ...
    x<2*quantile(x(x<xt),0.85)) | ...
    (y <= yt & ...
    y > 0);

% The bad
if numel(x)<40
    bad = (x>xt |...
        y < yt) & ~weird;
else
    bad = x>xt &...
        y < yt;
end
            
