function MovieHTML(varargin)
% http://www.mathworks.com/matlabcentral/answers/98217
% The ability to include AVI-files in the HTML-file generated by the
% PUBLISH command is not currently available in MATLAB. To work around this
% issue, you can modify your HTML-file manually to include an AVI file
% (created using MOVIE2AVI) that shows your movie. To do this, follow these
% steps:    
% 
% 1. Create an AVI file using MOVIE2AVI. Place this file in the "html"
% subdirectory created when you used the "Publish to HTML" option. (The
% subdirectory will be in the same directory as the original MATLAB file
% that you published.)   
% 
% 2. Open the MATLAB-generated HTML-file with the MATLAB Editor/Debugger or
% another text editor. This file will be in the "html" subdirectory and
% will have the same name as the original program file, but with the
% extension ".html" instead of ".m".   
% 
% 3. Find the place where the movie command appears in the HTML. After the
% "movie(...)" text, there will be an image in the HTML which contains the
% last frame of the movie. Remove the image and /image tags and everything
% in between.   
% 
% 4. In the spot in the HTML-file where the image was, add an AVI object to
% the HTML-file using the "object" tag, as in:    
% 
%  <object data="mymovie.avi" type="video/avi">
%  Text to Display if the Browser Doesn't Support AVI files.
%  </object>
% This will include the AVI file in your HTML-file. Please note that many
% browsers do not support AVI objects, and the security options in your
% browser may also prevent the display of AVI objects.  

if nargin
    filename = varargin{1};
    extnsn = filename(end-2:end);
else
    filename = 'mymovie.mp4';
    extnsn = 'mp4';
end

fprintf('<object data="%s" type="video/%s"> Browser Doesn''t Support AVI files. </object>\n',filename,extnsn)